# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kymera.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KymeraDialog(object):
    def setupUi(self, KymeraDialog):
        KymeraDialog.setObjectName("KymeraDialog")
        KymeraDialog.resize(398, 237)
        self.cWlEdit = QtWidgets.QLineEdit(KymeraDialog)
        self.cWlEdit.setGeometry(QtCore.QRect(140, 30, 71, 25))
        self.cWlEdit.setObjectName("cWlEdit")
        self.focusEdit = QtWidgets.QLineEdit(KymeraDialog)
        self.focusEdit.setGeometry(QtCore.QRect(140, 110, 71, 25))
        self.focusEdit.setObjectName("focusEdit")
        self.filterCombo = QtWidgets.QComboBox(KymeraDialog)
        self.filterCombo.setGeometry(QtCore.QRect(140, 70, 141, 25))
        self.filterCombo.setObjectName("filterCombo")
        self.gratingCombo = QtWidgets.QComboBox(KymeraDialog)
        self.gratingCombo.setGeometry(QtCore.QRect(140, 150, 141, 25))
        self.gratingCombo.setObjectName("gratingCombo")
        self.cWlButt = QtWidgets.QPushButton(KymeraDialog)
        self.cWlButt.setGeometry(QtCore.QRect(230, 30, 51, 25))
        self.cWlButt.setObjectName("cWlButt")
        self.focusButt = QtWidgets.QPushButton(KymeraDialog)
        self.focusButt.setGeometry(QtCore.QRect(230, 110, 51, 25))
        self.focusButt.setObjectName("focusButt")
        self.cWllabel = QtWidgets.QLabel(KymeraDialog)
        self.cWllabel.setGeometry(QtCore.QRect(40, 34, 71, 17))
        self.cWllabel.setObjectName("cWllabel")
        self.filterLabel = QtWidgets.QLabel(KymeraDialog)
        self.filterLabel.setGeometry(QtCore.QRect(70, 73, 41, 17))
        self.filterLabel.setObjectName("filterLabel")
        self.focusLabel = QtWidgets.QLabel(KymeraDialog)
        self.focusLabel.setGeometry(QtCore.QRect(33, 113, 81, 17))
        self.focusLabel.setObjectName("focusLabel")
        self.gratingLabel = QtWidgets.QLabel(KymeraDialog)
        self.gratingLabel.setGeometry(QtCore.QRect(56, 154, 61, 17))
        self.gratingLabel.setObjectName("gratingLabel")

        self.retranslateUi(KymeraDialog)
        QtCore.QMetaObject.connectSlotsByName(KymeraDialog)

    def retranslateUi(self, KymeraDialog):
        _translate = QtCore.QCoreApplication.translate
        KymeraDialog.setWindowTitle(_translate("KymeraDialog", "Kymera"))
        self.cWlButt.setText(_translate("KymeraDialog", "Set"))
        self.focusButt.setText(_translate("KymeraDialog", "Set"))
        self.cWllabel.setText(_translate("KymeraDialog", "Center WL:"))
        self.filterLabel.setText(_translate("KymeraDialog", "Filter:"))
        self.focusLabel.setText(_translate("KymeraDialog", "Focus steps:"))
        self.gratingLabel.setText(_translate("KymeraDialog", "Grating:"))
