# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\JYLambda.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LambdaDialog(object):
    def setupUi(self, LambdaDialog):
        LambdaDialog.setObjectName("LambdaDialog")
        LambdaDialog.resize(361, 193)
        self.verticalLayout = QtWidgets.QVBoxLayout(LambdaDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wlScaleBox = QtWidgets.QGroupBox(LambdaDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wlScaleBox.sizePolicy().hasHeightForWidth())
        self.wlScaleBox.setSizePolicy(sizePolicy)
        self.wlScaleBox.setMinimumSize(QtCore.QSize(330, 0))
        self.wlScaleBox.setObjectName("wlScaleBox")
        self.NeCheck1 = QtWidgets.QCheckBox(self.wlScaleBox)
        self.NeCheck1.setGeometry(QtCore.QRect(20, 30, 81, 20))
        self.NeCheck1.setChecked(True)
        self.NeCheck1.setObjectName("NeCheck1")
        self.startEdit = QtWidgets.QLineEdit(self.wlScaleBox)
        self.startEdit.setGeometry(QtCore.QRect(240, 70, 71, 20))
        self.startEdit.setObjectName("startEdit")
        self.stepEdit = QtWidgets.QLineEdit(self.wlScaleBox)
        self.stepEdit.setGeometry(QtCore.QRect(240, 110, 71, 20))
        self.stepEdit.setObjectName("stepEdit")
        self.label_2 = QtWidgets.QLabel(self.wlScaleBox)
        self.label_2.setGeometry(QtCore.QRect(190, 70, 41, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.wlScaleBox)
        self.label_4.setGeometry(QtCore.QRect(190, 110, 41, 16))
        self.label_4.setObjectName("label_4")
        self.calcLmbdButt = QtWidgets.QPushButton(self.wlScaleBox)
        self.calcLmbdButt.setGeometry(QtCore.QRect(260, 30, 75, 23))
        self.calcLmbdButt.setCheckable(False)
        self.calcLmbdButt.setObjectName("calcLmbdButt")
        self.NeCheck2 = QtWidgets.QCheckBox(self.wlScaleBox)
        self.NeCheck2.setGeometry(QtCore.QRect(20, 70, 81, 20))
        self.NeCheck2.setChecked(True)
        self.NeCheck2.setObjectName("NeCheck2")
        self.NeCheck3 = QtWidgets.QCheckBox(self.wlScaleBox)
        self.NeCheck3.setGeometry(QtCore.QRect(20, 110, 81, 20))
        self.NeCheck3.setChecked(True)
        self.NeCheck3.setObjectName("NeCheck3")
        self.fitPxelButt = QtWidgets.QPushButton(self.wlScaleBox)
        self.fitPxelButt.setGeometry(QtCore.QRect(180, 30, 75, 23))
        self.fitPxelButt.setCheckable(False)
        self.fitPxelButt.setObjectName("fitPxelButt")
        self.NeEdit1 = QtWidgets.QLineEdit(self.wlScaleBox)
        self.NeEdit1.setGeometry(QtCore.QRect(110, 30, 61, 20))
        self.NeEdit1.setObjectName("NeEdit1")
        self.NeEdit2 = QtWidgets.QLineEdit(self.wlScaleBox)
        self.NeEdit2.setGeometry(QtCore.QRect(110, 70, 61, 20))
        self.NeEdit2.setObjectName("NeEdit2")
        self.NeEdit3 = QtWidgets.QLineEdit(self.wlScaleBox)
        self.NeEdit3.setGeometry(QtCore.QRect(110, 110, 61, 20))
        self.NeEdit3.setObjectName("NeEdit3")
        self.verticalLayout.addWidget(self.wlScaleBox)

        self.retranslateUi(LambdaDialog)
        QtCore.QMetaObject.connectSlotsByName(LambdaDialog)

    def retranslateUi(self, LambdaDialog):
        _translate = QtCore.QCoreApplication.translate
        LambdaDialog.setWindowTitle(_translate("LambdaDialog", "╬╗ - scale"))
        self.wlScaleBox.setTitle(_translate("LambdaDialog", "╬╗ - scale"))
        self.NeCheck1.setText(_translate("LambdaDialog", "692.9 nm"))
        self.label_2.setText(_translate("LambdaDialog", "Start"))
        self.label_4.setText(_translate("LambdaDialog", "Step"))
        self.calcLmbdButt.setText(_translate("LambdaDialog", "Calc"))
        self.NeCheck2.setText(_translate("LambdaDialog", "693.8 nm Ar"))
        self.NeCheck3.setText(_translate("LambdaDialog", "696.5 nm"))
        self.fitPxelButt.setText(_translate("LambdaDialog", "Fit"))
        self.NeEdit1.setText(_translate("LambdaDialog", "355"))
        self.NeEdit2.setText(_translate("LambdaDialog", "470"))
        self.NeEdit3.setText(_translate("LambdaDialog", "858"))
        